### ISSUE TITLE
Add property to control if quarkus-zeebe-client is enabled or not

### ISSUE THREAD

**Issue by forszpanen** [quarkiverse/quarkus-zeebe#271] opened 2024-05-13 21:37 UTC
Hello :) we have use a case where Camunda Self-Managed is deployed only to some environments. Each env has more restrictions so aren't available at this same time. When dependency to quarkus-zeebe is added, client tries to connect by grpc and when there is no zeebe-gateway available application stops. I found that Spring-zeebe-client has sth similar: 
https://github.com/camunda-community-hub/spring-zeebe?tab=readme-ov-file#disabling-zeebeclient
but https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-client-zeebe/src/main/java/io/camunda/zeebe/spring/client/event/ZeebeClientCreatedEvent.java uses a different approach compare to quarkus-zeebe as I understand. Base on that I have a few questions:
1. What would you suggest to do if application stops when there is no Camunda engine configured? Add custom ZeebeHealthCheck or handle global exception?
2. What do you think about this property zeebe.client.enabled to have it in quarkus-zeebe? If you agree, what could be an idea how to do it? "Empty" implementation for ZeebeClientImpl? @andrejpetras

**Comment by andrejpetras** [comment] 2024-05-20 09:45
Duplicate of #169

**Closed by andrejpetras** 2024-05-20 09:45 UTC

**Comment by marcinstankiewicz** [comment] 2024-05-28 13:42
I need to reopen this topic.
I'm using new release 1.5.0 and if i put new variable quarkus.zeebe.active=false then my service pod (which is using quarkus-zeebe) is not starting due to health check. 
With quarkus.zeebe.active=true everything is ok.

![image](https://github.com/quarkiverse/quarkus-zeebe/assets/9077347/226d43fb-cd9e-4c18-950d-85e6953db978)
